#ifndef RGB_H
#define RGB_H

#define RING_NUM_LEDS 24
#define STRIP_NUM_LEDS 8
#define RGB_TOTAL_NUM_LED RING_NUM_LEDS + STRIP_NUM_LEDS
#define STRIP_LED_INDEX_START RING_NUM_LEDS
#define STRIP_LED_INDEX_END RGB_TOTAL_NUM_LED

enum { COLOR_RED, COLOR_GREEN, COLOR_BLUE };

#endif
